version: '3'

tasks:
  cmake:
    cmds:
      # - cmake -B build -S . -GNinja -DARGO_BENCHMARKS_ENABLE=true
      - cmake -B build -S . -GNinja -DARGO_TESTS_ENABLE=true -DARGO_BENCHMARKS_ENABLE=true
  compile:
    cmds:
      - cmake --build build
  execute:
    cmds:
      # - ./build/main --arg1=42 --arg2="Hello,World"
      # - ./build/test-parser-release
      - ./build/bench-parser-release
    silent: true
