version: '3'

tasks:
  cmake:
    cmds:
      - cmake -B build -S . -GNinja -DARGO_TESTS_ENABLE=true
  compile:
    cmds:
      - cmake --build build
  execute:
    cmds:
      - ./build/test-argo-release
    silent: true
