# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  cmake:
    cmds:
      - cmake -B build -S . -GNinja -DARGO_TESTS_ENABLE=true -DARGO_BENCHMARKS_ENABLE=true
    env:
      CC: /usr/local/opt/llvm/bin/clang
      CXX: /usr/local/opt/llvm/bin/clang++
  compile:
    cmds:
      - cmake --build build
  execute:
    cmds:
      # - ./build/main --arg1=42 --arg2="Hello,World"
      # - ./build/test-parser-release --gtest_filter=ArgoTest.CombiningFlagsWithOptionalArg
      - ./build/bench-parser-release
    silent: true
