version: '3'

tasks:
  cmake:
    cmds:
      - cmake -B build -S . -DARGO_TESTS_ENABLE=true -DARGO_BENCHMARKS_ENABLE=true -GNinja
  compile:
    cmds:
      - cmake --build build
  execute:
    cmds:
      - ./build/test-argo-release
    silent: true
