version: '3'

tasks:
  cmake:
    cmds:
      - cmake -B build -S . -DARGO_TESTS_ENABLE=true -DARGO_BENCHMARKS_ENABLE=true -GNinja
  compile:
    cmds:
      - cmake --build build
  execute:
    cmds:
      - ./build/test-argo-release
    silent: true
  report:
    cmds:
      - ./build/test-argo-debug &> /dev/null
      - $PROF_DATA merge -sparse ./build/test-argo-debug.profraw -o ./build/coverage.profdata
      - $LLVM_COV report ./build/test-argo-debug -instr-profile=./build/coverage.profdata -ignore-filename-regex="tests*"
    env:
      LLVM_PROFILE_FILE: ./build/test-argo-debug.profraw
      PROF_DATA: /usr/local/opt/llvm/bin/llvm-profdata
      LLVM_COV: /usr/local/opt/llvm/bin/llvm-cov
    silent: true
