name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}
  schedule:
    - cron: '0 23 * * SUN-THU'
  workflow_dispatch:

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upgrade homebrew
        run: |
          brew update
          brew install python@3.11 --force
          brew install node@18 --force
          brew upgrade
        continue-on-error: true

      - name: Install llvm
        run: |
          brew install llvm
        continue-on-error: true

      - name: Install googletest
        run: |
          brew install googletest
        continue-on-error: true

      - name: Install ninja
        run: |
          brew install ninja
        continue-on-error: true

      - name: Cmake and Compile
        run: |
          cmake -B build -S . -DARGO_TESTS_ENABLE=true -GNinja
          cmake --build build
        env:
          CC: /usr/local/opt/llvm/bin/clang
          CXX: /usr/local/opt/llvm/bin/clang++

      - name: Test Debug
        run: |
          ./build/test-argo-debug

      - name: Test Release
        run: |
          ./build/test-argo-release
